services:
    sqlserver:
        image: ${IMAGE:-mcr.microsoft.com/mssql/server:2022-latest}
        container_name: ${CONTAINER_NAME:-sqlserver}
        user: root
        volumes:
            - ./volumes/mssql/data:/var/opt/mssql/data
            - ./volumes/mssql/backups:/var/opt/mssql/backups
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "${SQL_SERVER_SA_PASSWORD:-A123456*}"
        ports:
            - ${SQL_SERVER_PORT:-1433}:1433
        restart: always
        networks:
            - sqlserver
        healthcheck:
            test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SQL_SERVER_SA_PASSWORD:-A123456*}" -C -Q "SELECT 1" || exit 1
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 60s
            start_interval: 5s

networks:
    sqlserver:
        name: sqlserver
