version: '3.8'

services:
    sqlserver:
        image: ${IMAGE:-mcr.microsoft.com/mssql/server:2022-latest}
        container_name: ${CONTAINER_NAME:-sqlserver}
        user: root
        volumes:
            - ./volumes/mssql/data:/var/opt/mssql/data
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "${SQL_SERVER_SA_PASSWORD:-A123456*}"
        ports:
            - ${SQL_SERVER_PORT:-1433}:1433
        restart: always
        networks:
            - sqlserver
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
            interval: 5s
            timeout: 3s
            retries: 50
            start_period: 10s

networks:
    sqlserver:
        name: sqlserver
