version: '3.8'

services:
    sqlserver:
        deploy:
            resources:
                limits:
                    memory: 2048M
                reservations:
                    memory: 1500M
